## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing PlayStore App Data

In [2]:
app_data = pd.read_csv('..\Data\Raw_Data\googleplaystore.csv')
app_data.head()

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\Om\AppData\Local\Temp\ipykernel_33372\3013374998.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  app_data = pd.read_csv('..\Data\Raw_Data\googleplaystore.csv')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

## Creating Copy of the Raw Dataset

In [3]:
app_df = app_data.copy()
app_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.2 MB

In [4]:
# Size of the dataset
print("Rows and Columns:", app_df.shape)

Rows and Columns: (10841, 13)

In [5]:
app_df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

## Fixing Null Values

In [6]:
# Checking for missing values
app_df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [7]:
# Replacing Rating Null values with Median
app_df['Rating'].fillna(app_df['Rating'].median(), inplace=True)

# Dropping rows with null values in Type and Content Rating
app_df = app_df.dropna(subset=["Type", "Content Rating"])

# Replacing null values in Current Ver and Android Ver with Unknown
app_df['Current Ver'].fillna('Unknown', inplace=True)
app_df['Android Ver'].fillna('Unknown', inplace=True)

C:\Users\Om\AppData\Local\Temp\ipykernel_33372\1189666078.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  app_df['Rating'].fillna(app_df['Rating'].median(), inplace=True)
C:\Users\Om\AppData\Local\Temp\ipykernel_33372\1189666078.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  app_df['Current Ver'].fillna('Unknown', inplace=True)
C:\Users\Om\AppData\Local\Temp\ipykernel_33372\1189666078.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  app_df['Android Ver'].fillna('Unknown', inplace=True)

0              4.0.3 and up
1              4.0.3 and up
2              4.0.3 and up
3                4.2 and up
4                4.4 and up
                ...
10836            4.1 and up
10837            4.1 and up
10838            2.2 and up
10839    Varies with device
10840    Varies with device
Name: Android Ver, Length: 10839, dtype: str

In [8]:
# Final check for missing values
app_df.isna().sum()

App                  0
Category             0
Rating            1473
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [9]:
# Validating that there are no more missing values
app_df[app_df["Rating"].isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61,7.0M,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,"March 7, 2018",1.0.0,4.1 and up
113,Wrinkles and rejuvenation,BEAUTY,NaN,182,5.7M,"100,000+",Free,0,Everyone 10+,Beauty,"September 20, 2017",8.0,3.0 and up
123,Manicure - nail design,BEAUTY,NaN,119,3.7M,"50,000+",Free,0,Everyone,Beauty,"July 23, 2018",1.3,4.1 and up
126,Skin Care and Natural Beauty,BEAUTY,NaN,654,7.4M,"100,000+",Free,0,Teen,Beauty,"July 17, 2018",1.15,4.1 and up
129,"Secrets of beauty, youth and health",BEAUTY,NaN,77,2.9M,"10,000+",Free,0,Mature 17+,Beauty,"August 8, 2017",2.0,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10824,Cardio-FR,MEDICAL,NaN,67,82M,"10,000+",Free,0,Everyone,Medical,"July 31, 2018",2.2.2,4.4 and up
10825,Naruto & Boruto FR,SOCIAL,NaN,7,7.7M,100+,Free,0,Teen,Social,"February 2, 2018",1.0,4.0 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up

In [10]:
# Dropping any remaining rows with null values in Rating, Current Ver and Android Ver
app_df = app_df.dropna(subset=["Rating", "Current Ver", "Android Ver"])

In [11]:
# Validating that there are no more missing values
app_df.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [12]:
# checking New size of the dataset
app_df.shape

(9360, 13)

## Fixing Duplicate Values

In [13]:
# Checking for duplicates
app_df.duplicated().sum()

np.int64(474)

In [14]:
# Identifying duplicate entries based on the App column
app_df[app_df["App"].duplicated(keep=False)].sort_values(by="App")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1393,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
1407,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
2322,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2543,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2256,2017 EMRA Antibiotic Guide,MEDICAL,4.4,12,3.8M,"1,000+",Paid,$16.99,Everyone,Medical,"January 27, 2017",1.0.5,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3103,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3118,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3202,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3652,wetter.com - Weather and Radar,WEATHER,4.2,189313,38M,"10,000,000+",Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device
8291,wetter.com - Weather and Radar,WEATHER,4.2,189310,38M,"10,000,000+",Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device

In [15]:
# Sorting by number of reviews and removing duplicates
app_df = app_df.sort_values(by="Reviews", ascending=False)

# Dropping duplicates based on the App column, keeping the first occurrence
app_df = app_df.drop_duplicates(subset="App", keep="first")

# Final check for duplicates based on the App column
print(app_df["App"].duplicated().sum())

0

In [16]:
app_df.shape

(8190, 13)

In [17]:
app_df.info()

<class 'pandas.DataFrame'>
Index: 8190 entries, 2989 to 10776
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8190 non-null   str
 1   Category        8190 non-null   str
 2   Rating          8190 non-null   float64
 3   Reviews         8190 non-null   str
 4   Size            8190 non-null   str
 5   Installs        8190 non-null   str
 6   Type            8190 non-null   str
 7   Price           8190 non-null   str
 8   Content Rating  8190 non-null   str
 9   Genres          8190 non-null   str
 10  Last Updated    8190 non-null   str
 11  Current Ver     8190 non-null   str
 12  Android Ver     8190 non-null   str
dtypes: float64(1), str(12)
memory usage: 1.7 MB

## Cleaning Size Column

In [18]:
# Checking unique values in the Size column
app_df["Size"].unique()[:20]

<ArrowStringArray>
[               '31M',                '91k',                '18M',
                '33M',                '22M', 'Varies with device',
               '5.5M',                '10M',                '38M',
               '3.7M',                '96M',                '15M',
                '97M',               '2.9M',               '2.8M',
               '3.9M',                '49M',               '3.2M',
                '75M',               '9.4M']
Length: 20, dtype: str

In [19]:
# Create a function to clean the Size column
def clean_size(size):
    if size == "Varies with device":
        return np.nan
    
    size = str(size)

    if "M" in size:
        return float(size.replace("M", ""))

    elif "k" in size:
        return float(size.replace("k", "")) / 1024

    else:
        return np.nan

In [20]:
# Applying the clean_size function to the Size column
app_df["Size"] = app_df["Size"].apply(clean_size)

In [21]:
# Checking the cleaned Size column
app_df["Size"] = app_df["Size"].fillna(app_df["Size"].median())

In [22]:
# Final check of the Size column
app_df["Size"].head()

2989    31.000000
4970     0.088867
2705    18.000000
3049    33.000000
3229    22.000000
Name: Size, dtype: float64

## Clean Install Column

In [23]:
# Checking unique values in the Installs column
app_df["Installs"].unique()[:10]

<ArrowStringArray>
[  '1,000,000+',     '100,000+',     '500,000+',      '50,000+',
  '10,000,000+',   '5,000,000+',      '10,000+',  '50,000,000+',
 '100,000,000+',       '5,000+']
Length: 10, dtype: str

In [24]:
# Cleaning the Installs column by removing + and , elements
app_df["Installs"] = (
    app_df["Installs"]
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

In [25]:
# Converting the Installs column to numeric, coercing errors to NaN
app_df["Installs"] = pd.to_numeric(
    app_df["Installs"],
    errors="coerce"
)

In [26]:
# Final check of the Installs column
app_df["Installs"].head()

2989    1000000
4970     100000
2705    1000000
3049    1000000
3229     500000
Name: Installs, dtype: int64

## Cleaning Price Column

In [27]:
# Checking unique values in the Price column
app_df["Price"] = (
    app_df["Price"]
    .str.replace("$", "", regex=False)
)

In [28]:
# Converting the Price column to numeric, coercing errors to NaN
app_df["Price"] = pd.to_numeric(
    app_df["Price"],
    errors="coerce"
)

In [29]:
# Final check of the Price column
app_df["Price"].head()

2989    0.0
4970    0.0
2705    0.0
3049    0.0
3229    0.0
Name: Price, dtype: float64

## Cleaning Review Column

In [30]:
# Checking unique values in the Reviews column
app_df["Reviews"] = pd.to_numeric(
    app_df["Reviews"],
    errors="coerce"
)

In [31]:
# Final check of the Reviews column
app_df["Reviews"].head()

2989    9992
4970     999
2705    9975
3049    9971
3229    9971
Name: Reviews, dtype: int64

## Cleaning Lastly updated Column

In [32]:
# Checking unique values in the Last Updated column
app_df["Last Updated"] = pd.to_datetime(
    app_df["Last Updated"],
    errors="coerce"
)

In [33]:
# Final check of the Last Updated column
app_df["Last Updated"].head()

2989   2018-05-23
4970   2013-12-17
2705   2018-01-22
3049   2018-06-05
3229   2018-08-06
Name: Last Updated, dtype: datetime64[us]

## Feature Engineering

In [34]:
# Extracting month and year from the Last Updated column
app_df["Updated_Month"] = app_df["Last Updated"].dt.month

# Extracting year from the Last Updated column
app_df["Updated_Year"] = app_df["Last Updated"].dt.year

# Final check of the Last Updated, Updated_Month and Updated_Year columns
app_df[["Last Updated", "Updated_Month", "Updated_Year"]].head()

     Last Updated  Updated_Month  Updated_Year
2989   2018-05-23              5          2018
4970   2013-12-17             12          2013
2705   2018-01-22              1          2018
3049   2018-06-05              6          2018
3229   2018-08-06              8          2018

## Final Check over the Dataset

In [ ]:
# final check of the dataset
app_df.describe(include = "all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Updated_Month,Updated_Year
count,8190,8190,8190.000000,8.190000e+03,8190.000000,8.190000e+03,8190,8190.000000,8190,8190,8190,8190,8190,8190.000000,8190.000000
unique,8190,33,NaN,NaN,NaN,NaN,2,NaN,6,115,NaN,2625,31,NaN,NaN
top,GollerCepte Live Score,FAMILY,NaN,NaN,NaN,NaN,Free,NaN,Everyone,Tools,NaN,Varies with device,4.1 and up,NaN,NaN
freq,1,1650,NaN,NaN,NaN,NaN,7588,NaN,6612,717,NaN,1011,1812,NaN,NaN
mean,NaN,NaN,4.173162,2.554323e+05,20.513488,9.174798e+06,NaN,1.038342,NaN,NaN,2017-11-05 09:52:21.098901,NaN,NaN,6.388523,2017.359341
min,NaN,NaN,1.000000,1.000000e+00,0.008301,1.000000e+00,NaN,0.000000,NaN,NaN,2010-05-21 00:00:00,NaN,NaN,1.000000,2010.000000
25%,NaN,NaN,4.000000,1.260000e+02,5.800000,1.000000e+04,NaN,0.000000,NaN,NaN,2017-08-17 00:00:00,NaN,NaN,5.000000,2017.000000
50%,NaN,NaN,4.300000,3.009500e+03,13.000000,1.000000e+05,NaN,0.000000,NaN,NaN,2018-05-20 00:00:00,NaN,NaN,7.000000,2018.000000
75%,NaN,NaN,4.500000,4.385075e+04,27.000000,1.000000e+06,NaN,0.000000,NaN,NaN,2018-07-19 00:00:00,NaN,NaN,8.000000,2018.000000
max,NaN,NaN,5.000000,7.815831e+07,100.000000,1.000000e+09,NaN,400.000000,NaN,NaN,2018-08-08 00:00:00,NaN,NaN,12.000000,2018.000000
std,NaN,NaN,0.536589,1.986395e+06,21.267158,5.827353e+07,NaN,16.864040,NaN,NaN,NaN,NaN,NaN,2.598827,1.146251

In [36]:
app_df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
Updated_Month     0
Updated_Year      0
dtype: int64

In [37]:
print(app_df.shape)

(8190, 15)

In [ ]:
# Saving the cleaned dataset to a new CSV file
app_df.to_csv("..\Data\Cleaned_Data\cleaned_app_data.csv", index=False)

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\Om\AppData\Local\Temp\ipykernel_33372\1304093139.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  app_df.to_csv("..\Data\Cleaned_Data\cleaned_app_data.csv", index=False)